const translations = {
  th: {
    carnow: "ข้อมูลรถยนต์รุ่นล่าสุด",
    carhave: "รถยนต์ที่มี",
    more: "เพิ่มเติม",
    list: "รายการที่บันทึก",
    lists: "รายการ",
    search: "ค้นหา",
    home: "หน้าแรก",
    photo: "ถ่ายรูป",
    edit: "แก้ไขข้อมูล",
    about: "ข้อมูลแอปพลิเคชัน",
    takephotocar: "ถ่ายรูปรถยนต์",
    takephotocarpart: "ถ่ายรูปชิ้นส่วนรถยนต์",
    total: "ยอดรวม",
    baht: "บาท",
    logout: "ออกจากระบบ",
    email: "กรอกอีเมล",
    password: "กรอกรหัสผ่าน",
    newpassword: "กรอกรหัสผ่านใหม่",
    confirmpassword: "กรอกรหัสผ่านอีกรอบ",
    forgotpassword: "ลืมรหัสผ่าน",
    confirm: "ยืนยัน",
    login: "เข้าสู่ระบบ",
    register: "สมัครสมาชิก",
    version: "เวอร์ชัน",
    account: "ยังไม่มีบัญชี ?",
    resetpassword: "รีเซ็ตรหัสผ่าน",
    haveaccount: "มีบัญชีอยู่แล้ว ?",
    wrongemail: "รูปแบบอีเมลไม่ถูกต้อง",
    wrongpassword: "รหัสผ่านต้องมากกว่า 6 ตัวขึ้นไป",
    wrongconfirmpass: "รหัสผ่านไม่ตรงกัน",
    alertupload: "อัปโหลดรูปภาพให้ครบทุกส่วน",
    carfront: "ด้านหน้ารถยนต์",
    carbehind: "ด้านหลังรถยนต์",
    carside: "ด้านข้างรถยนต์",
    process: "ประมวลผล",
    howtophoto: "คำแนะนำในการถ่ายรูป",
    howtophotocar: "คำแนะนำในการถ่ายรูปรถยนต์",
    howtophotocarpart: "คำแนะนำในการถ่ายรูปชิ้นส่วนรถยนต์",
    examplephoto: "ตัวอย่างในการถ่ายรูปภาพ",
    frontbumper: "กันชนหน้า",
    rearbumper: "กันชนหลัง",
    grille: "กระจังหน้า",
    door: "ประตู",
    headlamp: "ไฟหน้า",
    backuplamp: "ไฟท้าย",
    mirror: "กระจกข้าง",
    processresult: "ผลลัพธ์การประมวลผล",
    confident: "มั่นใจ",
    back: "ย้อนกลับ",
    seepartlist: "ดูรายการอะไหล่",
    seelist: "รายการอะไหล่",
    summary: "สรุปรายการ",
    summarypart: "สรุปรายการอะไหล่",
    code: "รหัสอะไหล่",
    name: "ชื่ออะไหล่",
    price: "ราคา (บาท)",
    parts: "ชิ้นส่วน",
    createbill: "สร้างใบรายการ",
    carpart: "อะไหล่รถยนต์",
    frontbumperpart: "อะไหล่กันชนหน้า",
    rearbumperpart: "อะไหล่กันชนหลัง",
    grillepart: "อะไหล่กระจังหน้า",
    headlamppart: "อะไหล่ไฟหน้า",
    backuplamppart: "อะไหล่ไฟท้าย",
    doorpart: "อะไหล่ประตู",
    mirrorpart: "อะไหล่กระจกข้าง",
    partlist: "รายการอะไหล่",
    choose: "เลือก",
    notsale: "ไม่วางขาย",
    bill: "ใบรายการ",
    billpart: "ใบรายการอะไหล่ชิ้นส่วนรถยนต์",
    imgprocess: "ทำการประมวลผลรูปภาพ",
    wait: "โปรดรอ 2-3 นาที",
    savelist: "บันทึกรายการ",
    detail:
      "ในปัจจุบันการใช้เทคโนโลยีในด้านประกันภัยเริ่มได้รับความนิยมมากขึ้นทางเราได้สนใจเกี่ยวกับปัญหาการระบุอัตลักษณ์รถยนต์ที่เกิดจากความหลากหลายของรถยนต์บนท้องถนน และการค้นหาอะไหล่ของรถยนต์ทำให้เราสนใจที่จะใช้เทคโนโลยีโครงข่ายประสาทเทียมแบบคอนโวลูชัน โดนเลือกใช้โมเดลการเรียนรู้เชิงลึก Resnet50, VGG16 และ MobileNetV2 เพื่อนำแต่ละโมเดลมาเปรียบเทียบร่วมกับชุดข้อมูลรถยนต์ทั่วไปที่พบได้บ่อยในประเทศไทย ทั้งหมด 18 รุ่นโดยประกอบด้วยรูปภาพรถยนต์ทั้งคัน 1,864 รูป และรูปภาพของชิ้นส่วนรถยนต์ทั้ง 5 ส่วนได้แก่ รูปภาพชิ้นส่วนกันชนหน้า 810 รูป รูปภาพชิ้นส่วนกันชนหลัง 729 รูป รูปภาพชิ้นส่วนประตู 785 รูป รูปภาพชิ้นส่วนไฟหน้า 805 รูป และ รูปภาพชิ้นส่วนไฟท้าย 842 รูป เพื่อนำไปใช้ในการพัฒนาโมเดลการเรียนรู้เชิงลึกที่สามารถระบุอัตลักษณ์ของรถยนต์ผ่านรูปภาพรถยนต์ทั้งคัน และรูปภาพชิ้นส่วนของรถยนต์ ซึ่งจะถูกนำไปใช้ในแอปพลิเคชันมือถือเพื่อให้ผู้ใช้งานสามารถถ่ายรูปภาพรถยนต์ หรือชิ้นส่วนรถยนต์ หรือนำรูปภาพจากคลังรูปภาพในอุปกรณ์มือถือมาระบุรถยนต์และสามารถดูข้อมูลอะไหล่ของชิ้นส่วนรถยนต์ที่ระบุได้",
    changepass: "เปลี่ยนรหัสผ่านของคุณ",
    textalertpass: "เปลี่ยนรหัสผ่านเรียบร้อยแล้ว",
    carpartlists: 'รายการชิ้นส่วนรถยนต์',
    alertuploadtext: 'กรุณาอัปโหลดรูปกันชนหน้าหรือไฟหน้าอย่างน้อย 1 รูปภาพ'
    // requirement: "ข้อกำหนดและเงื่อนไขในการสมัครสมาชิก",
    // userreq: "ผู้ใช้ที่สมัครสมาชิกจะต้องยินยอมข้อกำหนด และ เงื่อนไขการใช้งานแอปพลิเคชัน Carnan ดังต่อไปนี้",
  },
  en: {
    carnow: "Latest car models",
    carhave: "My car",
    more: "More",
    list: "Record list",
    lists: "List",
    search: "Search",
    home: "Home",
    photo: "Take photo",
    edit: "Edit profile",
    about: "About us",
    takephotocar: "Take photos of a car",
    takephotocarpart: "Take photos of a car parts",
    total: "Total",
    baht: "Baht",
    logout: "Log out",
    email: "Enter email",
    password: "Enter password",
    newpassword: "Enter new password",
    confirmpassword: "Enter confirm password",
    forgotpassword: "Forgot password",
    confirm: "Confirm",
    login: "Login",
    register: "Register",
    version: "Version",
    account: "Don't have an account yet ?",
    resetpassword: "Reset password",
    haveaccount: "Already have an account ?",
    wrongemail: "Invalid email format",
    wrongpassword: "Password must be at least 6 characters",
    wrongconfirmpass: "Passwords don't match",
    alertupload: "All picture must be uploaded.",
    carfront: "Car Front",
    carbehind: "Car Behind",
    carside: "Car Side",
    process: "Process",
    howtophoto: "How to Take a Photos",
    howtophotocar: "How to Take Cars Photos",
    howtophotocarpart: "How to Take Auto Parts Photos",
    examplephoto: "Example of taking pictures",
    frontbumper: "Front Bumper",
    rearbumper: "Rear Bumper",
    grille: "Grille",
    door: "Door",
    headlamp: "HeadLamp",
    backuplamp: "Backup Lamp",
    mirror: "Side Car Mirror",
    processresult: "Processing results",
    confident: "Confident",
    back: "Back",
    seepartlist: "See Parts List",
    summary: "Summary list",
    summarypart: "Parts List",
    seelist: "Parts List",
    code: "Parts code",
    name: "Parts name",
    price: "Price(Baht)",
    parts: "Parts",
    createbill: "Create a bill",
    carpart: "Car Parts",
    frontbumperpart: "Front Bumper Parts",
    rearbumperpart: "Rear Bumper Parts",
    grillepart: "Grille Parts",
    headlamppart: "HeadLamp Parts",
    backuplamppart: "Backup Lamp Parts",
    doorpart: "Door Parts",
    mirrorpart: "Side Car Mirror Parts",
    partlist: "Parts List",
    choose: "Choose",
    notsale: "Not for sale",
    bill: "Bill",
    billpart: "Bill's Auto Parts",
    imgprocess: "image processing",
    wait: "Please wait 2-3 minutes",
    savelist: "Save a list",
    detail: "At present, the use of technology in the insurance industry has been gaining increasing popularity.  We are interested in the car identification problem caused by the variety of cars on the road and finding car parts. This has led us to consider utilizing Convolutional Neural Network technology, as well as deep learning models such as Resnet50, VGG16 and MobileNetV2 for car identification.  And a car dataset that is commonly found in Thailand 18 models and consisting of a total of 1,864 images of whole cars and 5 parts, including 810 images of front bumper parts, 729 images of rear bumper parts, 785 images of door parts, 805 images of headlight parts, and Tail light parts 842 images to be used for developing deep learning models that can identify car identities through images of the entire car and pictures of car parts. And will be used in mobile applications.  So that users take pictures of cars or car parts or pick an image from the user's photo library to identify a car and be able to view spare parts information for specific car part",
    changepass: "Change your password",
    textalertpass: "Password changed successfully",
    carpartlists: 'carpartlist',
    alertuploadtext: 'Must upload at least 1 picture of front bumper or headlamp'

    // requirement: "Terms and Conditions for Memberships",
    // userreq: "Users who apply for membership must agree to the following terms and conditions of use of the Carnan application."
  },
};

export default translations;
